#!/usr/bin/env python3
"""
Pull the portal into MongoDB.

    python ingest.py                      roles + assessments + submissions
    python ingest.py --skip-roles         submissions only (fast; no admin crawl)
    python ingest.py --roles-only         roles + assessments only
    python ingest.py --review-status new  only the untouched queue
    python ingest.py --resumes            fetch + extract resume text (only)

Three stages:

  1. Crawl every role and its LIVE assessment markdown, writing each role's
     assessment to assessments/<slug>.md so it can be reviewed in git.
  2. Download the submissions CSV -- one request per review queue, `new` and
     `pending` by default -- and upsert each record, answer text included.
  3. Apply the missing-artefact rule, moving submissions into `rejected` or
     `pending`.

Safe to re-run. Portal-owned fields are overwritten every time; our own
decisions and evaluations are never touched by stages 1-2, and stage 3 will not
overwrite a decision a human made.

--resumes is a fourth stage that runs on its own and is never part of the three
above: the first backfill is ~3,700 requests to third-party hosts, and nothing
consumes the text it stores yet.
"""

import argparse
import csv
import io
import logging
import sys
import threading
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from typing import Optional, Sequence

import requests
from pymongo.errors import PyMongoError

from config import (
    ASSESSMENT_DIR,
    INGEST_REVIEW_BUCKETS,
    PORTAL_SUBMISSIONS_CSV,
    REQUIRED_ARTEFACTS,
)
import mongo_store as store
import portal_crawler
import resume_reader
from portal_scraper import REVIEW_BUCKETS, _download, _login
from reminder import setup_logging

log = logging.getLogger("ingest")

# Answer text is free-form and unbounded; one record can span many lines.
csv.field_size_limit(10_000_000)

INT_FIELDS = ("submission_id", "job_id")


def _clean(value) -> str:
    return (value or "").strip()


# ---------------------------------------------------------------------------
# Stage 1 -- roles and assessments
# ---------------------------------------------------------------------------

def ingest_roles() -> dict:
    """Crawl roles + live assessments into Mongo and assessments/<slug>.md."""
    roles, assessments = portal_crawler.crawl(with_assessments=True)
    if not roles:
        log.error("No roles crawled -- check portal credentials.")
        return {"roles": 0, "assessments": 0}

    store.upsert_roles(roles)

    ASSESSMENT_DIR.mkdir(exist_ok=True)
    by_id = {r["job_id"]: r for r in roles}
    written = 0
    for job_id, assessment in assessments.items():
        store.set_role_assessment(job_id, assessment)
        role = by_id.get(job_id, {})
        slug = role.get("slug") or str(job_id)
        # newline="" keeps the portal's CRLF out of the file on Windows, so the
        # same text round-trips instead of showing up as a diff on every crawl.
        path = ASSESSMENT_DIR / f"{slug}.md"
        header = (
            f"<!-- Crawled from {assessment.get('url')} -- "
            f"{assessment.get('name')} {assessment.get('version') or ''}. "
            f"Regenerated by ingest.py; edit rubric-{slug}.md instead. -->\n\n"
        )
        path.write_text(header + assessment["markdown"], encoding="utf-8", newline="\n")
        written += 1

    log.info("Roles: %d stored, %d assessments written to %s",
             len(roles), written, ASSESSMENT_DIR.name)
    return {"roles": len(roles), "assessments": written}


# ---------------------------------------------------------------------------
# Stage 2 -- submissions
# ---------------------------------------------------------------------------

def _parse_row(row: dict) -> Optional[dict]:
    """One CSV row as a submission document, or None if it is not a record."""
    sid = _clean(row.get("submission_id"))
    if not sid.isdigit():
        return None                        # header artefact or blank trailing row
    rec = {k: _clean(v) for k, v in row.items()}
    for field in INT_FIELDS:
        rec[field] = int(rec[field]) if rec[field].isdigit() else None
    rec["candidate_email"] = rec.get("candidate_email", "").lower()
    # Keep the answer text verbatim -- _clean would strip leading markdown.
    rec["submission_markdown"] = row.get("submission_markdown") or ""
    return rec


def resolve_buckets(buckets: Optional[Sequence[str]] = None) -> tuple[str, ...]:
    """
    Normalise a review-queue selection, rejecting anything the portal does not
    recognise.

    Validated rather than passed through because the portal answers an unknown
    review_status with the default "new" rows and a 200. A typo would therefore
    produce a run that looks entirely successful while fetching the same queue
    twice and never touching the one that was asked for.
    """
    chosen = tuple(b.strip().lower() for b in (buckets or INGEST_REVIEW_BUCKETS)
                   if b and b.strip())
    if not chosen:
        raise ValueError("No review queues selected.")
    unknown = [b for b in chosen if b not in REVIEW_BUCKETS]
    if unknown:
        raise ValueError(
            f"Unknown portal review status: {', '.join(unknown)}. "
            f"Valid values are {', '.join(REVIEW_BUCKETS)}."
        )
    # dict.fromkeys rather than set(): duplicates would fetch 11 MB twice, and
    # the given order is the order they get logged in.
    return tuple(dict.fromkeys(chosen))


def fetch_submission_rows(
    buckets: Optional[Sequence[str]] = None,
) -> tuple[list[dict], list[str]]:
    """
    Download and parse the portal's CSV export, one review queue at a time.

    Never the bare export URL on its own. That URL carries a hidden filter and
    returns only review_status "new", which silently excludes the Pending
    Review queue -- candidates who submitted and are waiting on a verdict.
    Those are exactly as ungradeable-by-a-human and exactly as worth evaluating
    as the untouched ones, so both queues are fetched. See
    INGEST_REVIEW_BUCKETS in config.py for why the settled queues are not.

    Also never the full export: it pulls in ~1,500 candidates a reviewer has
    already decided on, and grade.py would spend tokens re-scoring them.

    Per queue rather than in one request because the combined body is large
    enough that the portal usually drops it -- the same reason portal_scraper.py
    reassembles it in pieces, whose retrying downloader this shares.

    Returns (records, failed_buckets). A queue that will not download costs its
    own rows and nothing else: the records that did arrive are still worth
    storing, since upserts are additive and stage 3 reads the whole store rather
    than this run's rows. The caller reports what was missed.
    """
    try:
        chosen = resolve_buckets(buckets)
    except ValueError as exc:
        log.error("%s", exc)
        return [], list(buckets or INGEST_REVIEW_BUCKETS)

    session = _login()
    if session is None:
        return [], list(chosen)

    # Keyed by submission_id: a record a reviewer moves from one queue to
    # another mid-fetch would otherwise be stored twice.
    records: dict[int, dict] = {}
    failed: list[str] = []

    log.info("Downloading review queues: %s", ", ".join(chosen))
    for bucket in chosen:
        body = _download(
            session,
            f"{PORTAL_SUBMISSIONS_CSV}?review_status={bucket}",
            f"review_status={bucket}",
        )
        if body is None:
            log.error(
                "The '%s' queue would not download. Its candidates are not in "
                "this run -- re-run ingest to pick them up.", bucket,
            )
            failed.append(bucket)
            continue

        parsed = 0
        before = len(records)
        for row in csv.DictReader(io.StringIO(body)):
            rec = _parse_row(row)
            if rec is None:
                continue
            parsed += 1
            records[rec["submission_id"]] = rec
        log.info("  %-10s %d row(s), %d new to this run",
                 bucket, parsed, len(records) - before)

    log.info("Portal: %d submission record(s) downloaded across %d queue(s).",
             len(records), len(chosen) - len(failed))
    return list(records.values()), failed


def ingest_submissions(buckets: Optional[Sequence[str]] = None) -> dict:
    records, failed = fetch_submission_rows(buckets)
    if not records:
        return {"downloaded": 0, "new": 0, "updated": 0, "failed_queues": failed}
    result = store.upsert_submissions(records)
    log.info("Submissions: %d new, %d updated.", result["upserted"], result["matched"])
    if failed:
        log.warning("Incomplete sync: %s did not download.", ", ".join(failed))
    return {
        "downloaded": len(records),
        "new": result["upserted"],
        "updated": result["matched"],
        "failed_queues": failed,
    }


# ---------------------------------------------------------------------------
# Stage 3 -- the missing-artefact rule
# ---------------------------------------------------------------------------

def apply_auto_rejections() -> dict:
    """
    Sort submitted candidates into `rejected` or `pending`.

    A candidate missing a required artefact is rejected outright: there is
    nothing to grade. Everyone else becomes `pending`, which is the queue the
    grader reads from.

    The portal's own review state does not enter into this. Whether a candidate
    arrived from the untouched queue or from Pending Review, the question here
    is the same one -- is there anything to mark? -- and the answer is the same.

    Two things are deliberately left alone: any decision a human made
    (source == "manual"), and anyone already scored -- re-running ingest must
    never silently discard a review or a paid-for evaluation.
    """
    counts = {"rejected": 0, "pending": 0, "in_progress": 0, "skipped": 0}

    for sub in store.list_submissions(include_markdown=False):
        decision = sub.get("decision") or {}
        if decision.get("source") == "manual" or decision.get("status") == "scored":
            counts["skipped"] += 1
            continue

        if sub.get("submission_status") != "submitted":
            # Started but never finished -- not a rejection, just not ready.
            if decision.get("status") != "in_progress":
                store.set_decision(sub["_id"], "in_progress", "not_submitted", "auto")
            counts["in_progress"] += 1
            continue

        missing = [f for f in REQUIRED_ARTEFACTS if not _clean(sub.get(f))]
        if missing:
            reason = "missing_" + "_and_".join(f.replace("_link", "") for f in missing)
            if decision.get("status") != "rejected" or decision.get("reason") != reason:
                store.set_decision(sub["_id"], "rejected", reason, "auto")
            counts["rejected"] += 1
        else:
            if decision.get("status") != "pending":
                store.set_decision(sub["_id"], "pending", "awaiting_evaluation", "auto")
            counts["pending"] += 1

    log.info(
        "Screening: %d rejected (missing artefact), %d pending evaluation, "
        "%d still in progress, %d left alone (manual or scored).",
        counts["rejected"], counts["pending"], counts["in_progress"], counts["skipped"],
    )
    return counts


# ---------------------------------------------------------------------------
# Resumes -- opt-in, never part of the normal sync
# ---------------------------------------------------------------------------

# Six at a time. The work is almost entirely waiting on Google, so this is not
# CPU-bound, but 3,700 requests from one IP is exactly the shape of traffic
# Drive starts refusing -- and a 429 is indistinguishable from a private file
# once it is stored as an error.
RESUME_WORKERS = 6

# Progress every N rows. Measured at roughly 45 rows a minute, so a full
# backfill runs for well over an hour; a run that printed nothing until the end
# would be indistinguishable from a hung one.
RESUME_LOG_EVERY = 100


def ingest_resumes(retry_errors: bool = False, limit: int = 0,
                   workers: int = RESUME_WORKERS,
                   transient_only: bool = False) -> dict:
    """
    Fetch each candidate's resume and store the extracted text.

    Deliberately not wired into run(): the first backfill is ~3,700 requests to
    third-party hosts, which is not something a routine sync -- or a cron job --
    should carry. It is its own command, and it is re-runnable, so the normal
    way to use it is to run it after an ingest and let it skip everything it
    already did.

    Failures are the common case, not the exception -- see resume_reader's
    docstring for the measured breakdown. Every one is stored as a reason
    string and the run carries on.
    """
    pending = store.needs_resume(retry_errors=retry_errors, limit=limit,
                                 transient_only=transient_only)
    if not pending:
        log.info("Resumes: nothing to fetch -- every submitted candidate's "
                 "resume_link has already been read.")
        return {"attempted": 0, "extracted": 0, "failed": 0}

    log.info("Resumes: %d to fetch, %d at a time.", len(pending), workers)

    # One session per worker thread, not one shared across them. A Session is
    # not documented as thread-safe, and the failure it produces under load is
    # a connection error indistinguishable from a private file once stored.
    # Per-thread keeps the keep-alive benefit without the sharing.
    local = threading.local()

    def session() -> requests.Session:
        if not hasattr(local, "session"):
            local.session = requests.Session()
        return local.session

    counts = {"attempted": 0, "extracted": 0, "failed": 0}
    reasons: Counter = Counter()

    def read_one(doc: dict) -> tuple[dict, str, str]:
        link = (doc.get("resume_link") or "").strip()
        text, error = resume_reader.read_resume(link, session())
        return doc, text, error

    # A write that fails on one document is that document's problem; a write
    # that fails on ten in a row is the database, and carrying on would mean
    # fetching 3,000 more resumes with nowhere to put them.
    consecutive_write_failures = 0
    MAX_CONSECUTIVE = 10

    with ThreadPoolExecutor(max_workers=workers) as pool:
        for doc, text, error in pool.map(read_one, pending):
            link = (doc.get("resume_link") or "").strip()
            # Written one row at a time rather than batched at the end, so a
            # run that is interrupted keeps everything it had already read.
            try:
                store.set_resume(doc["_id"], text, error, link)
                consecutive_write_failures = 0
            except PyMongoError as exc:
                # The first backfill died here, on a resume holding half of a
                # surrogate pair that BSON would not encode. resume_reader
                # cleans that at the source now; this is the backstop for the
                # next unencodable thing a PDF produces, because losing the
                # remaining rows costs far more than losing this one.
                consecutive_write_failures += 1
                counts["attempted"] += 1
                counts["failed"] += 1
                reasons["write_failed"] += 1
                log.warning("Could not store resume for submission %s: %s",
                            doc["_id"], exc)
                if consecutive_write_failures >= MAX_CONSECUTIVE:
                    log.error(
                        "%d consecutive write failures -- stopping. This is the "
                        "database, not the resumes. %d row(s) stored so far are "
                        "kept; re-run to continue.",
                        consecutive_write_failures, counts["attempted"],
                    )
                    break
                continue
            counts["attempted"] += 1
            if error:
                counts["failed"] += 1
                reasons[error.split(":")[0]] += 1
            else:
                counts["extracted"] += 1
            if counts["attempted"] % RESUME_LOG_EVERY == 0:
                log.info("  %d/%d -- %d extracted, %d failed",
                         counts["attempted"], len(pending),
                         counts["extracted"], counts["failed"])

    log.info("Resumes: %d attempted, %d extracted, %d failed.",
             counts["attempted"], counts["extracted"], counts["failed"])
    if reasons:
        log.info("Resume failures: %s",
                 ", ".join(f"{r}={n}" for r, n in reasons.most_common()))
    counts["reasons"] = dict(reasons)
    return counts


# ---------------------------------------------------------------------------

def run(
    skip_roles: bool = False,
    roles_only: bool = False,
    review_buckets: Optional[Sequence[str]] = None,
) -> dict:
    store.ping()
    store.ensure_indexes()

    summary: dict = {}
    if not skip_roles:
        summary["roles"] = ingest_roles()
    if not roles_only:
        summary["submissions"] = ingest_submissions(review_buckets)
        summary["screening"] = apply_auto_rejections()
    return summary


def _report(summary: dict) -> None:
    """Print the per-stage one-liners every command ends with."""
    print("\nIngest complete:")
    for stage, data in summary.items():
        parts = ", ".join(
            f"{k}={','.join(v) if isinstance(v, list) else v}"
            for k, v in data.items()
            if not isinstance(v, dict) and (v or not isinstance(v, list))
        )
        print(f"  {stage}: {parts}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-roles", action="store_true",
                        help="submissions only; skip the admin crawl")
    parser.add_argument("--roles-only", action="store_true",
                        help="roles and assessments only")
    parser.add_argument(
        "--review-status", metavar="LIST",
        help=("comma-separated portal review queues to pull, from "
              f"{', '.join(REVIEW_BUCKETS)} "
              f"(default: {', '.join(INGEST_REVIEW_BUCKETS)})"),
    )
    parser.add_argument("--resumes", action="store_true",
                        help="fetch and extract resume text; runs on its own, "
                             "skipping links already read")
    parser.add_argument("--retry-errors", action="store_true",
                        help="with --resumes, re-attempt every link that failed")
    parser.add_argument("--retry-transient", action="store_true",
                        help="with --resumes, re-attempt only the failures worth "
                             "retrying (rate limits, timeouts, dropped "
                             "connections) -- run this after a long backfill")
    parser.add_argument("--limit", type=int, default=0, metavar="N",
                        help="with --resumes, stop after N resumes")
    parser.add_argument("--workers", type=int, default=RESUME_WORKERS,
                        metavar="N",
                        help=(f"with --resumes, parallel fetches "
                              f"(default {RESUME_WORKERS}); drop to 2 for a "
                              "retry pass after a throttled run"))
    args = parser.parse_args()

    setup_logging()

    # Its own command, not a stage of the sync: the first backfill is ~3,700
    # third-party requests, and nothing consumes the text yet.
    if args.resumes:
        try:
            store.ping()
            summary = {"resumes": ingest_resumes(
                retry_errors=args.retry_errors, limit=args.limit,
                transient_only=args.retry_transient,
                workers=max(1, args.workers))}
        except store.MongoUnavailable as exc:
            log.error("%s", exc)
            return 1
        _report(summary)
        stats = store.resume_stats()
        print(f"\n  {stats['extracted']} of {stats['with_link']} submitted "
              f"candidates now have resume text "
              f"({stats['failed']} unreadable, "
              f"{stats['with_link'] - stats['attempted']} not yet attempted).")
        spread = store.resume_error_spread()
        if spread:
            print("\n  Why they failed:")
            for reason, n in spread[:12]:
                print(f"    {n:5d}  {reason}")
        return 0

    buckets = args.review_status.split(",") if args.review_status else None
    try:
        # Validated up front so a typo fails on the command line rather than
        # after the roles crawl -- and rather than quietly fetching "new" twice.
        resolve_buckets(buckets)
    except ValueError as exc:
        log.error("%s", exc)
        return 1

    try:
        summary = run(skip_roles=args.skip_roles, roles_only=args.roles_only,
                      review_buckets=buckets)
    except store.MongoUnavailable as exc:
        log.error("%s", exc)
        return 1

    _report(summary)

    # A queue that would not download is not a failed run -- the rest of the
    # sync stands -- but it is a run whose grading queue is short, so it gets
    # its own exit code for a cron wrapper to retry on.
    if (summary.get("submissions") or {}).get("failed_queues"):
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main())
